server:
  port: 7877

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://81.71.96.88:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: PCBBoardDetection@2025-4-23@114yajyusenpai514###1919810!

logging:
  level:
    com.work.commonconfig.config: DEBUG
    com.alibaba.druid: DEBUG
