server:
  port: 7878

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: detection-service

eureka:
  client:
    service-url:
      defaultZone: http://81.71.96.88:8761/eureka/