server:
  port: 9934

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors: # 全局CORS配置（关键点）
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"  # 允许前端地址
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS  # 必须允许OPTIONS方法
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600  # 预检请求缓存时间
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0

        - id: detection-service
          uri: lb://detection-service
          predicates:
            - Path=/detection/**
          filters:
            - StripPrefix=0

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
